// Tempel file ini ke Google Apps Script yang terikat pada Google Spreadsheet.
var CONFIG = { TIMEZONE: 'Asia/Jakarta', SHEETS: { DOCTORS: 'Doctors', SERVICES: 'Services', SCHEDULES: 'Schedules', BOOKINGS: 'Bookings' }, LOCK_TIMEOUT_MS: 15000 };

function jsonResponse(data) { return ContentService.createTextOutput(JSON.stringify(data)).setMimeType(ContentService.MimeType.JSON); }
function rows(name) { var s = SpreadsheetApp.getActive().getSheetByName(name); if (!s || s.getLastRow() < 2) return []; var values = s.getDataRange().getValues(), headers = values.shift(); return values.map(function(row) { var item = {}; headers.forEach(function(h, i) { item[String(h).trim()] = row[i]; }); return item; }); }
function active(value) { return value === true || ['TRUE', '1', 'YES'].indexOf(String(value).toUpperCase()) >= 0; }
function doctors() { return rows(CONFIG.SHEETS.DOCTORS).filter(function(x) { return active(x.active); }).map(function(x) { return { id: String(x.doctor_id), name: String(x.name), specialization: String(x.specialization || ''), calendarId: String(x.calendar_id || 'primary') }; }); }
function services() { return rows(CONFIG.SHEETS.SERVICES).filter(function(x) { return active(x.active); }).map(function(x) { return { id: String(x.service_id), name: String(x.name), description: String(x.description || ''), durationMinutes: Number(x.duration_minutes) || 60, price: Number(x.price) || 0 }; }); }
function find(list, id) { return list.filter(function(x) { return x.id === id; })[0]; }
function mins(value) { if (value instanceof Date) return value.getHours() * 60 + value.getMinutes(); var m = String(value).replace('.', ':').match(/(\d{1,2}):(\d{2})/); return m ? Number(m[1]) * 60 + Number(m[2]) : 0; }
function hhmm(n) { return ('0' + Math.floor(n / 60)).slice(-2) + ':' + ('0' + n % 60).slice(-2); }
function dateTime(date, time) { var d = date.split('-'), t = time.split(':'); return new Date(Number(d[0]), Number(d[1]) - 1, Number(d[2]), Number(t[0]), Number(t[1])); }
function calendar(id) { return id && id !== 'primary' ? (CalendarApp.getCalendarById(id) || CalendarApp.getDefaultCalendar()) : CalendarApp.getDefaultCalendar(); }
function conflict(id, start, end) { return calendar(id).getEvents(start, end).some(function(e) { return !e.isAllDayEvent() && e.getStartTime() < end && e.getEndTime() > start; }); }
function getSlots(p) { var doc = find(doctors(), p.doctorId), srv = find(services(), p.serviceId); if (!doc || !srv) return []; var day = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][dateTime(p.date, '00:00').getDay()]; var schedules = rows(CONFIG.SHEETS.SCHEDULES).filter(function(x) { return String(x.doctor_id) === p.doctorId && active(x.active) && String(x.day_of_week).toLowerCase() === day.toLowerCase(); }); var result = []; schedules.forEach(function(x) { for (var n = mins(x.start_time); n + srv.durationMinutes <= mins(x.end_time); n += srv.durationMinutes) { var start = dateTime(p.date, hhmm(n)), end = dateTime(p.date, hhmm(n + srv.durationMinutes)); if (!conflict(doc.calendarId, start, end)) result.push({ start: hhmm(n), end: hhmm(n + srv.durationMinutes) }); } }); return result; }
function createBooking(p) { var doc = find(doctors(), String(p.doctorId || '')), srv = find(services(), String(p.serviceId || '')); if (!doc || !srv || !p.date || !p.startTime || !p.customerName || !p.phone) return { success: false, code: 'VALIDATION_ERROR', message: 'Data booking belum lengkap.' }; var end = mins(p.startTime) + srv.durationMinutes, endTime = hhmm(end), start = dateTime(p.date, p.startTime), finish = dateTime(p.date, endTime), lock = LockService.getScriptLock(); if (!lock.tryLock(CONFIG.LOCK_TIMEOUT_MS)) return { success: false, code: 'SERVER_BUSY', message: 'Sistem sedang sibuk, coba lagi.' }; try { if (conflict(doc.calendarId, start, finish)) return { success: false, code: 'SLOT_UNAVAILABLE', message: 'Slot sudah diambil, silakan pilih waktu lain.' }; var id = 'BK-' + p.date.replace(/-/g, '').slice(2) + '-' + Math.floor(100 + Math.random() * 900), mode = p.consultationMode === 'online' ? 'Online' : 'Offline', title = 'Booking ' + mode + ' - ' + p.customerName; var event = calendar(doc.calendarId).createEvent(title, start, finish, { description: 'Booking ID: ' + id + '\nCustomer: ' + p.customerName + '\nPhone: ' + p.phone + '\nLayanan: ' + srv.name + '\nMode: ' + mode + '\nCatatan: ' + (p.notes || ''), location: mode === 'Offline' ? 'Lumière Beauté' : 'Konsultasi Online' }); var sheet = SpreadsheetApp.getActive().getSheetByName(CONFIG.SHEETS.BOOKINGS) || SpreadsheetApp.getActive().insertSheet(CONFIG.SHEETS.BOOKINGS); if (sheet.getLastRow() === 0) sheet.appendRow(['booking_id','customer_name','phone','email','doctor_id','doctor_name','service_id','service_name','consultation_mode','date','start_time','end_time','status','notes','google_event_id','created_at']); sheet.appendRow([id,p.customerName,p.phone,p.email || '',doc.id,doc.name,srv.id,srv.name,p.consultationMode || 'offline',p.date,p.startTime,endTime,'CONFIRMED',p.notes || '',event.getId(),Utilities.formatDate(new Date(), CONFIG.TIMEZONE, 'yyyy-MM-dd HH:mm:ss')]); return { success: true, data: { bookingId: id, customerName: p.customerName, serviceName: srv.name, doctorName: doc.name, consultationMode: p.consultationMode || 'offline', date: p.date, startTime: p.startTime, endTime: endTime, status: 'CONFIRMED' } }; } finally { lock.releaseLock(); } }
function doGet(e) { try { var p = e.parameter || {}; if (p.action === 'getDoctors') return jsonResponse({ success: true, data: doctors() }); if (p.action === 'getServices') return jsonResponse({ success: true, data: services() }); if (p.action === 'getAvailableSlots') return jsonResponse({ success: true, data: getSlots(p) }); return jsonResponse({ success: false, message: 'Action tidak dikenali.' }); } catch (e) { return jsonResponse({ success: false, message: e.message }); } }
function doPost(e) { try { var p = JSON.parse(e.postData.contents); return jsonResponse(createBooking(p)); } catch (e) { return jsonResponse({ success: false, message: e.message }); } }
